### ISSUE TITLE
Infografia da mettere sotto la descrizione della devfest

### ISSUE THREAD

**Issue by bonfry** [gdgbari/2023-web-devfest#3]
Feedback di michela:

n home metterei una cosa simile con il n delle track al posto dei gg:

![image](https://github.com/gdgbari/2023-web-devfest/assets/37514317/aea9e566-baf2-4996-8b08-aa72dbc41006)

Potremmo inserirlo nel blocco della descrizione della devfest:
- partecipanti (500)
- speaker (25)
- categorie di talk (10)
- track (4)

**Comment by domysh** [comment]
@bonfry Ho creato la grafica nel branch [number-homepage](https://github.com/gdgbari/2023-web-devfest/tree/number-homepage).

Gli svg non mi piacciono troppo ma non so dove trovarli (uso solitamente react-icons), e mi sembra che quello per "Categories" sia un po' più grande degli altri, se hai un sito migliore per gli svg linkamelo o sostituisci tu stesso i file

**Comment by bonfry** [comment]
Io mi trovo molto bene con questo icon pack di material design https://pictogrammers.com/library/mdi/
